on:
    push:
        branches:
            - develop

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: erlef/setup-beam@v1
              with:
                  otp-version: 24
                  elixir-version: 1.12.2
            - run: mix deps.get
            - run: mix docs
            - uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./doc
